# Generated by Django 5.1 on 2024-09-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_username_user_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_temporary',
            field=models.BooleanField(default=True),
        ),
    ]
