# Generated by Django 5.1 on 2024-09-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_is_password_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_password_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
