# Generated by Django 5.1 on 2024-09-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_is_password_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new_password',
            field=models.BooleanField(default=False),
        ),
    ]
