# Generated by Django 4.2.16 on 2024-09-12 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_is_new_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='confirmation',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='user',
        ),
        migrations.AddField(
            model_name='kyc',
            name='Date_Of_Birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='kyc',
            name='UserName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='document_file_back',
            field=models.FileField(blank=True, upload_to='kyc_documents/back/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='document_file_front',
            field=models.FileField(blank=True, upload_to='kyc_documents/front/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='email',
            field=models.EmailField(default=1, max_length=254, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
