# Generated by Django 4.2.16 on 2024-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_confirmation_kyc_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
