# Generated by Django 4.2.16 on 2026-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_strategy_execution_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategies',
            name='multi_leg_template',
            field=models.CharField(blank=True, choices=[('SHORT_STRADDLE', 'Short Straddle'), ('BULL_CALL_SPREAD', 'Bull Call Spread'), ('BEAR_CALL_SPREAD', 'Bear Call Spread'), ('BEAR_PUT_SPREAD', 'Bear Put Spread'), ('LONG_CALL_BUTTERFLY', 'Long Call Butterfly'), ('SHORT_CALL_BUTTERFLY', 'Short Call Butterfly'), ('LONG_CALL_CONDOR', 'Long Call Condor'), ('SHORT_CALL_CONDOR', 'Short Call Condor'), ('LONG_IRON_CONDOR', 'Long Iron Condor'), ('SHORT_IRON_BUTTERFLY', 'Short Iron Butterfly')], max_length=40, null=True),
        ),
    ]
