# Generated by Django 4.2.16 on 2024-09-18 09:19

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_permission_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
        ),
    ]
