# Generated by Django 4.2.16 on 2026-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_strategies_multi_leg_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmultilegstrategysetting',
            name='underlying',
            field=models.CharField(blank=True, default='NIFTY', max_length=30, null=True),
        ),
    ]
