# Generated by Django 4.2.16 on 2026-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clientmultilegstrategysetting_underlying'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmultilegstrategysetting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientmultilegstrategysetting',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
