# Generated by Django 4.2.16 on 2024-09-19 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_panel_client_key_user_client_type_user_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='kyc',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc', to=settings.AUTH_USER_MODEL),
        ),
    ]
