# Generated by Django 4.2.16 on 2026-05-08 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_clientmultilegstrategysetting_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('provider', models.CharField(blank=True, max_length=150, null=True)),
                ('server_url', models.URLField(max_length=500)),
                ('node_id', models.CharField(max_length=120, unique=True)),
                ('node_secret', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('free', 'Free'), ('assigned', 'Assigned'), ('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled')], db_index=True, default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified_with_broker', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_node', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clientbrokerdetails',
            name='execution_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_details', to='main.executionnode'),
        ),
        migrations.CreateModel(
            name='ExecutionOrderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('order_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_to_node', 'Sent to node'), ('accepted_by_node', 'Accepted by node'), ('placed', 'Placed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('node_response', models.JSONField(blank=True, null=True)),
                ('broker_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_order_jobs', to='main.clientbrokerdetails')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_order_jobs', to=settings.AUTH_USER_MODEL)),
                ('execution_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_jobs', to='main.executionnode')),
            ],
            options={
                'indexes': [models.Index(fields=['execution_node'], name='main_execut_executi_0436ee_idx'), models.Index(fields=['status'], name='main_execut_status_6acced_idx'), models.Index(fields=['created_at'], name='main_execut_created_e41355_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionNodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_node_logs', to=settings.AUTH_USER_MODEL)),
                ('execution_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.executionnode')),
            ],
            options={
                'indexes': [models.Index(fields=['execution_node'], name='main_execut_executi_1b3c7a_idx'), models.Index(fields=['created_at'], name='main_execut_created_7a0727_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='executionnode',
            index=models.Index(fields=['assigned_client'], name='main_execut_assigne_26e28e_idx'),
        ),
        migrations.AddIndex(
            model_name='executionnode',
            index=models.Index(fields=['status'], name='main_execut_status_a5111f_idx'),
        ),
        migrations.AddIndex(
            model_name='executionnode',
            index=models.Index(fields=['created_at'], name='main_execut_created_6c8950_idx'),
        ),
    ]
