# Generated by Django 4.2.16 on 2026-05-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_executionnode_clientbrokerdetails_execution_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionnode',
            name='execution_type',
            field=models.CharField(choices=[('vps_node', 'VPS Node'), ('proxy', 'Proxy')], db_index=True, default='vps_node', max_length=20),
        ),
        migrations.AddField(
            model_name='executionnode',
            name='proxy_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='executionnode',
            name='proxy_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionnode',
            name='proxy_last_seen_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionnode',
            name='proxy_last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionnode',
            name='proxy_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionnode',
            name='proxy_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionnode',
            name='proxy_protocol',
            field=models.CharField(blank=True, choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks5', 'SOCKS5')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='executionnode',
            name='proxy_public_ip_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='executionnode',
            name='proxy_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='executionorderjob',
            name='execution_type',
            field=models.CharField(choices=[('vps_node', 'VPS Node'), ('proxy', 'Proxy')], db_index=True, default='vps_node', max_length=20),
        ),
        migrations.AddField(
            model_name='executionorderjob',
            name='proxy_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='executionnode',
            name='node_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='executionnode',
            name='server_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='executionorderjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_to_node', 'Sent to node'), ('accepted_by_node', 'Accepted by node'), ('proxy_routing', 'Proxy routing'), ('placed', 'Placed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='executionnode',
            index=models.Index(fields=['execution_type'], name='main_execut_executi_19f506_idx'),
        ),
    ]
