# Generated by Django 4.2.16 on 2024-09-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_kyc_status_kyc_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='Date_Of_Birth',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='UserName',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
    ]
