# Generated by Django 4.2.16 on 2026-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_executionnode_execution_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='executionorderjob',
            index=models.Index(fields=['client'], name='main_execut_client__7173ce_idx'),
        ),
        migrations.AddIndex(
            model_name='executionorderjob',
            index=models.Index(fields=['execution_type'], name='main_execut_executi_4c2cb9_idx'),
        ),
    ]
