# Generated by Django 4.2.16 on 2024-09-27 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_orderlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='document_type',
            new_name='id_proof',
        ),
        migrations.AddField(
            model_name='kyc',
            name='address_prof_back',
            field=models.FileField(blank=True, upload_to='kyc_documents/address_back/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='address_prof_front',
            field=models.FileField(blank=True, upload_to='kyc_documents/address_front/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='address_proof_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        # migrations.AddField(
        #     model_name='kyc',
        #     name='user',
        #     field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
    ]
