# Generated by Django 4.2.16 on 2026-05-28 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_expand_broker_api_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('upstox', 'Upstox')], max_length=50, unique=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('encrypted_api_secret', models.TextField(blank=True, null=True)),
                ('request_token', models.TextField(blank=True, null=True)),
                ('encrypted_access_token', models.TextField(blank=True, null=True)),
                ('encrypted_refresh_token', models.TextField(blank=True, null=True)),
                ('access_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('token_status', models.CharField(blank=True, default='inactive', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tokenCreatedAt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_data_credentials', to='main.executionnode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
