# Generated by Django 4.2.16 on 2024-09-30 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_document_type_kyc_id_proof_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='kyc',
        #     name='user',
        #     field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='orderlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
