# Generated by Django 4.2.16 on 2026-05-29 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_marketdatacredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(db_index=True, default=main.models.get_ist_time)),
                ('created_at', models.DateTimeField(default=main.models.get_ist_time)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_subadmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chat_threads', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('client', 'Client'), ('subadmin', 'Subadmin'), ('superadmin', 'Superadmin')], max_length=20)),
                ('message', models.TextField()),
                ('is_read_by_client', models.BooleanField(default=False)),
                ('is_read_by_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=main.models.get_ist_time)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chatthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['client', 'status'], name='main_chatth_client__a710d3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['assigned_subadmin', 'status'], name='main_chatth_assigne_4259f2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['last_message_at'], name='main_chatth_last_me_d52041_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='main_chatme_thread__7c294f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender_role'], name='main_chatme_sender__88d4e8_idx'),
        ),
    ]
