# Generated by Codex on 2026-06-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_harden_sltp_trade_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalAgreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("content_hash", models.CharField(db_index=True, editable=False, max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_legal_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ClientAgreementAcceptance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("agreement_version", models.CharField(max_length=50)),
                ("terms_version_hash", models.CharField(db_index=True, max_length=64)),
                ("client_name", models.CharField(blank=True, default="", max_length=300)),
                ("client_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("client_mobile", models.CharField(blank=True, default="", max_length=30)),
                ("accepted_at", models.DateTimeField(db_index=True, default=main.models.get_ist_time)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to=main.models.agreement_pdf_upload_path)),
                ("pdf_generated_at", models.DateTimeField(blank=True, null=True)),
                ("client_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("admin_email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("PDF_GENERATED", "PDF Generated"),
                            ("EMAIL_SENT", "Email Sent"),
                            ("EMAIL_FAILED", "Email Failed"),
                        ],
                        default="ACCEPTED",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("PDF_GENERATED", "PDF Generated"),
                            ("EMAIL_SENT", "Email Sent"),
                            ("EMAIL_FAILED", "Email Failed"),
                        ],
                        default="ACCEPTED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="main.legalagreement",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="legalagreement",
            constraint=models.UniqueConstraint(fields=("version",), name="unique_legal_agreement_version"),
        ),
        migrations.AddConstraint(
            model_name="legalagreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_active=True),
                fields=("is_active",),
                name="unique_active_legal_agreement",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientagreementacceptance",
            constraint=models.UniqueConstraint(fields=("client", "agreement"), name="unique_client_agreement_acceptance"),
        ),
    ]
