# Generated by Django 4.2.16 on 2024-10-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_kyc_user_user_country_user_state_user_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
