# Generated by Django 4.2.16 on 2026-07-08 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_allow_client_deletion_with_legal_acceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTradeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('BUY_CE', 'BUY CE'), ('BUY_PE', 'BUY PE')], max_length=20)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PREVIEW', max_length=20)),
                ('preview_count', models.PositiveIntegerField(default=0)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_trade_batches', to='main.groupservice')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_trade_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualTradeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(blank=True, max_length=100, null=True)),
                ('broker_status', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SKIPPED', 'Skipped'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.CharField(blank=True, max_length=120, null=True)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.manualtradebatch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_trade_results', to=settings.AUTH_USER_MODEL)),
                ('trade_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_trade_results', to='main.clienttradesetting')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'status'], name='main_manual_batch_i_2ef6c1_idx'), models.Index(fields=['client', 'created_at'], name='main_manual_client__91b0b7_idx')],
                'unique_together': {('batch', 'client')},
            },
        ),
        migrations.AddIndex(
            model_name='manualtradebatch',
            index=models.Index(fields=['status', 'created_at'], name='main_manual_status_f3e3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='manualtradebatch',
            index=models.Index(fields=['idempotency_key'], name='main_manual_idempot_0d4ac9_idx'),
        ),
    ]
