# Generated by Django 4.2.16 on 2024-10-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_user_current_address_user_permanent_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address_line1',
            new_name='Address_line1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address_line2',
            new_name='Address_line2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current_address',
            new_name='Current_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='permanent_address',
            new_name='Permanent_address',
        ),
    ]
