# Generated by Django 4.2.16 on 2024-10-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_address_line1_user_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middleName',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
