# Generated by Django 4.2.16 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_manual_trade_batches"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_place_manual_trades",
            field=models.BooleanField(default=False),
        ),
    ]
