# Generated by Codex on 2026-07-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_execution_node_assignments(apps, schema_editor):
    ExecutionNode = apps.get_model("main", "ExecutionNode")
    ExecutionNodeAssignment = apps.get_model("main", "ExecutionNodeAssignment")
    for node in ExecutionNode.objects.exclude(assigned_client_id__isnull=True):
        ExecutionNodeAssignment.objects.get_or_create(
            execution_node_id=node.id,
            client_id=node.assigned_client_id,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_subadmindashboardannouncement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionNodeAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_execution_node_assignments", to=settings.AUTH_USER_MODEL)),
                ("client", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="execution_node_assignment", to=settings.AUTH_USER_MODEL)),
                ("execution_node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="client_assignments", to="main.executionnode")),
            ],
        ),
        migrations.AddIndex(model_name="executionnodeassignment", index=models.Index(fields=["execution_node", "created_at"], name="main_execut_executi_b24aaa_idx")),
        migrations.AddIndex(model_name="executionnodeassignment", index=models.Index(fields=["client"], name="main_execut_client__a87c8a_idx")),
        migrations.RunPython(backfill_execution_node_assignments, migrations.RunPython.noop),
    ]
