# Generated by Django 4.2.16 on 2024-10-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_useractivitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivitylog',
            old_name='login_time',
            new_name='last_login_time',
        ),
        migrations.RenameField(
            model_name='useractivitylog',
            old_name='logout_time',
            new_name='last_logout_time',
        ),
    ]
