# Generated by Django 4.2.16 on 2024-10-08 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_kyc_user_alter_user_middlename'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='kyc',
        #     name='user',
        #     field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='useractivitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
