# Generated by Django 4.2.16 on 2024-10-09 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_kyc_user_useractivitylog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
