from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("main", "0029_aws_ami_node_claim")]

    operations = [
        migrations.CreateModel(
            name="BrokerOrderIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("kind", models.CharField(choices=[("entry", "Entry"), ("exit", "Exit")], db_index=True, max_length=10)),
                ("broker", models.CharField(db_index=True, max_length=40)),
                ("account_partition", models.CharField(db_index=True, max_length=96)),
                ("source_type", models.CharField(max_length=32)),
                ("source_id", models.CharField(max_length=96)),
                ("exit_generation", models.PositiveIntegerField(default=0)),
                ("lifecycle_state", models.CharField(choices=[("triggered", "Triggered"), ("queued", "Queued"), ("submitting", "Submitting"), ("broker_accepted", "Broker Accepted"), ("partial", "Partial"), ("filled", "Filled"), ("reconciled", "Reconciled"), ("submission_uncertain", "Submission Uncertain"), ("retryable_failure", "Retryable Failure"), ("manual_attention", "Manual Attention"), ("cancelled", "Cancelled")], db_index=True, default="triggered", max_length=32)),
                ("trigger_sources", models.JSONField(blank=True, default=list)),
                ("contract_snapshot", models.JSONField(blank=True, default=dict)),
                ("requested_quantity", models.PositiveIntegerField(default=0)),
                ("remaining_quantity", models.PositiveIntegerField(default=0)),
                ("filled_quantity", models.PositiveIntegerField(default=0)),
                ("fencing_token", models.PositiveBigIntegerField(default=0)),
                ("owner_token", models.CharField(blank=True, max_length=160)),
                ("heartbeat_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("reserved", "Reserved"), ("published", "Published"), ("submitting", "Submitting"), ("acknowledged", "Acknowledged"), ("ambiguous", "Ambiguous"), ("reconciling", "Reconciling"), ("rejected", "Rejected"), ("dead_letter", "Dead Letter"), ("cancelled", "Cancelled")], db_index=True, default="reserved", max_length=20)),
                ("stream_name", models.CharField(blank=True, max_length=96)),
                ("stream_message_id", models.CharField(blank=True, max_length=64)),
                ("consumer", models.CharField(blank=True, max_length=128)),
                ("broker_order_id", models.CharField(blank=True, max_length=255)),
                ("broker_status", models.CharField(blank=True, max_length=80)),
                ("outcome", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("reconcile_after", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("submission_started_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("broker_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="broker_order_intents", to="main.user")),
                ("exit_trade_history", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="broker_exit_intents", to="main.tradeorderhistory")),
            ],
        ),
        migrations.CreateModel(
            name="BrokerOrderFill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("broker_order_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("broker_trade_id", models.CharField(blank=True, max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=4, max_digits=15)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_fill", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("intent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fills", to="main.brokerorderintent")),
            ],
        ),
        migrations.AddIndex(model_name="brokerorderintent", index=models.Index(fields=["status", "created_at"], name="intent_status_created_idx")),
        migrations.AddIndex(model_name="brokerorderintent", index=models.Index(fields=["broker", "kind", "status"], name="main_intent_broker_kind_idx")),
        migrations.AddIndex(model_name="brokerorderintent", index=models.Index(fields=["account_partition", "created_at"], name="intent_account_created_idx")),
        migrations.AddIndex(model_name="brokerorderintent", index=models.Index(fields=["exit_trade_history", "lifecycle_state"], name="intent_exit_lifecycle_idx")),
        migrations.AddIndex(model_name="brokerorderintent", index=models.Index(fields=["kind", "lifecycle_state", "created_at"], name="intent_kind_lifecycle_idx")),
        migrations.AddConstraint(model_name="brokerorderintent", constraint=models.UniqueConstraint(condition=models.Q(("exit_trade_history__isnull", False)), fields=("kind", "exit_trade_history", "exit_generation"), name="unique_exit_generation_per_buy")),
        migrations.AddIndex(model_name="brokerorderfill", index=models.Index(fields=["intent", "created_at"], name="broker_fill_intent_time_idx")),
        migrations.AddConstraint(model_name="brokerorderfill", constraint=models.UniqueConstraint(fields=("intent", "broker_order_id", "broker_trade_id"), name="unique_broker_fill_per_intent")),
    ]
