# Generated by Django 4.2.16 on 2024-10-10 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_groupservice_kyc_user'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='kyc',
        #     name='user',
        #     field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
    ]
