# Generated by Django 4.2.16 on 2026-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_broker_order_intents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbrokerdetails',
            name='buffer_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.001, help_text='Buffer percentage for limit orders (0.001 to 10.0). Default: 0.001%', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='clientmultilegstrategysetting',
            name='buffer_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='clienttradesetting',
            name='buffer_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
