# Generated by Django 4.2.16 on 2026-09-11 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_allow_precise_limit_buffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrderTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=40)),
                ('broker_order_id', models.CharField(max_length=255)),
                ('side', models.CharField(max_length=4)),
                ('state', models.CharField(default='WAITING', max_length=24)),
                ('first_seen_at', models.DateTimeField()),
                ('pending_since', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.CharField(blank=True, default='', max_length=36)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_snapshot', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_order_timeouts', to='main.tradeorderhistory')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_check_at'], name='pending_timeout_due_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pendingordertimeout',
            constraint=models.UniqueConstraint(fields=('client', 'broker', 'broker_order_id'), name='pending_timeout_order_unique'),
        ),
    ]
