# Generated by Django 4.2.16 on 2024-10-10 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_state_kyc_user_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='updated_at',
        ),
    
    ]
