# Generated by Django 4.2.16 on 2024-10-10 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_cities_created_at_remove_cities_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Address_line1',
            new_name='current_add_line_1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Address_line2',
            new_name='current_add_line_2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='City',
            new_name='current_city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Country',
            new_name='current_country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='State',
            new_name='current_state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Zip_code',
            new_name='current_zip_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Current_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Permanent_address',
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_add_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_add_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
