# Generated by Django 4.2.16 on 2024-10-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_kyc_user_services_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ManyToManyField(related_name='services', to='main.categories'),
        ),
    ]
