# Generated by Django 4.2.16 on 2024-10-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_services_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liecense',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='liecense',
            old_name='no_of_month',
            new_name='no_of_days_month',
        ),
        migrations.RemoveField(
            model_name='groupservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='license',
        ),
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupservice',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupservice',
            name='segment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_Segments', to='main.segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupservice',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liecense',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='short_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='services',
            name='segment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_segments', to='main.segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='Lots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_categories', to='main.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services_categories', to='main.categories'),
            preserve_default=False,
        ),
    ]
