# Generated by Django 4.2.16 on 2024-10-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_title_liecense_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liecense',
            new_name='License',
        ),
    ]
