# Generated by Django 4.2.16 on 2024-10-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_liecense_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='no_of_days_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
