# Generated by Django 4.2.16 on 2024-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_license_no_of_days_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='period',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
