# Generated by Django 4.2.16 on 2024-10-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_license_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='half_yearly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='quarterly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='yearly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
