# Generated by Django 4.2.16 on 2024-10-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_strategy_half_yearly_amount_strategy_monthly_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Lots', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_submit', models.BooleanField(default=True)),
                ('Indicator', models.ImageField(blank=True, null=True, upload_to='strategy/Indicator')),
                ('Strategy_Tester', models.ImageField(blank=True, null=True, upload_to='strategy/Strategy_Tester')),
                ('Strategy_Logo', models.ImageField(blank=True, null=True, upload_to='strategy/Strategy_Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('quarterly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('half_yearly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('yearly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_categories', to='main.categories')),
                ('segment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_segments', to='main.segment')),
            ],
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
