# Generated by Django 4.2.16 on 2024-10-16 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_kyc_user_alter_strategies_half_yearly_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
