# Generated by Django 4.2.16 on 2024-10-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_orderlog_order_type_alter_orderlog_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_Broker', to='main.broker'),
        ),
        migrations.AddField(
            model_name='user',
            name='Group_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_Service', to='main.groupservice'),
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_license', to='main.license'),
        ),
        migrations.AddField(
            model_name='user',
            name='to_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
