# Generated by Django 4.2.16 on 2024-10-19 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
