# Generated by Django 4.2.16 on 2024-10-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_user_assigned_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
