# Generated by Django 4.2.16 on 2024-10-19 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_user_type_of_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_clients',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
