# Generated by Django 4.2.16 on 2024-10-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_user_assigned_clients_user_assigned_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
