# Generated by Django 4.2.16 on 2024-10-22 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_user_client_status_user_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Strategy',
            field=models.ManyToManyField(blank=True, related_name='client_strategy', to='main.strategies'),
        ),
        migrations.AddField(
            model_name='user',
            name='client_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='client_secrete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='demate_acc_uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='service_given_to_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='main.state'),
        ),
        migrations.AlterField(
            model_name='groupservice',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_Segments', to='main.segment'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_otp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role', to='main.role'),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_categories', to='main.categories'),
        ),
        migrations.AlterField(
            model_name='services',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_segments', to='main.segment'),
        ),
        migrations.AlterField(
            model_name='strategies',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_categories', to='main.categories'),
        ),
        migrations.AlterField(
            model_name='strategies',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_segments', to='main.segment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_Broker', to='main.broker'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Group_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_Service', to='main.groupservice'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_license', to='main.license'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.role'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activty_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
