# Generated by Django 4.2.16 on 2024-10-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_user_strategy_user_client_key_user_client_secrete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_date_client',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date_client',
            field=models.DateField(blank=True, null=True),
        ),
    ]
