# Generated by Django 4.2.16 on 2024-10-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_user_end_date_client_user_start_date_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='service_given_to_month',
            new_name='user_license_month',
        ),
        migrations.AddField(
            model_name='user',
            name='givenservices_to_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
