# Generated by Django 4.2.16 on 2024-10-24 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_rename_service_given_to_month_user_user_license_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategies',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
    ]
