# Generated by Django 4.2.16 on 2024-11-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_strategies_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_address_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='license',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
