# Generated by Django 4.2.16 on 2024-11-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_user_is_address_same_alter_license_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='demate_acc_uid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
