# Generated by Django 4.2.16 on 2024-11-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_user_buy_or_sell_user_expiry_user_product_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name': 'Segment', 'verbose_name_plural': 'Segments'},
        ),
        migrations.AddField(
            model_name='segment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_segments', to='main.segment'),
        ),
    ]
