# Generated by Django 4.2.16 on 2024-11-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_segment_options_segment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={},
        ),
        migrations.RemoveField(
            model_name='segment',
            name='parent',
        ),
        migrations.CreateModel(
            name='SubSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BooleanField(default=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_segments', to='main.segment')),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
            },
        ),
    ]
