# Generated by Django 4.2.16 on 2024-11-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_segment_options_remove_segment_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsegment',
            options={},
        ),
        migrations.CreateModel(
            name='ClientSegmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('trade_limit', models.PositiveIntegerField()),
                ('Product_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Max_Loss_For_Day', models.CharField(blank=True, max_length=50, null=True)),
                ('Min_Loss_For_Day', models.CharField(blank=True, max_length=50, null=True)),
                ('Max_Profit_For_Day', models.CharField(blank=True, max_length=50, null=True)),
                ('Min_Profit_For_Day', models.CharField(blank=True, max_length=50, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.broker')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_settings', to='main.segment')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.strategies')),
                ('sub_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_settings', to='main.subsegment')),
            ],
        ),
    ]
