# Generated by Django 4.2.16 on 2024-11-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_subsegment_options_clientsegmentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_trad_settings',
            field=models.ManyToManyField(blank=True, related_name='user_trading_settings', to='main.clientsegmentsetting'),
        ),
    ]
