# Generated by Django 4.2.16 on 2024-11-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_tradesetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradesetting',
            old_name='created_at',
            new_name='current_date',
        ),
        migrations.RemoveField(
            model_name='tradesetting',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='tradesetting',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='broker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='buy_sell',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='max_loss_for_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='max_profit_for_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='min_loss_for_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='min_profit_for_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='product_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='strategy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
