# Generated by Django 4.2.16 on 2024-11-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_rename_created_at_tradesetting_current_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesetting',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='trade_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
