# Generated by Django 4.2.16 on 2024-11-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_alter_tradesetting_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradeSetting',
            new_name='ClientTradeSetting',
        ),
        migrations.RemoveField(
            model_name='user',
            name='buy_or_sell',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client_trad_settings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='segments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tread_limit',
        ),
        migrations.DeleteModel(
            name='ClientSegmentSetting',
        ),
    ]
