# Generated by Django 4.2.16 on 2024-11-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_rename_tradesetting_clienttradesetting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttradesetting',
            old_name='is_status',
            new_name='is_tread_status',
        ),
    ]
