# Generated by Django 4.2.16 on 2024-11-21 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_rename_is_status_clienttradesetting_is_tread_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('is_trade_status', models.BooleanField()),
                ('trade_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_logs', to=settings.AUTH_USER_MODEL)),
                ('trade_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_logs', to='main.clienttradesetting')),
            ],
        ),
    ]
