# Generated by Django 4.2.16 on 2024-11-21 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_user_fullname_alter_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttradesetting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clienttradesetting',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.segment'),
        ),
        migrations.AlterField(
            model_name='clienttradesetting',
            name='sub_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subsegment'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='is_trade_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
