# Generated by Django 4.2.16 on 2024-11-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_alter_clienttradesetting_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='to_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
