# Generated by Django 4.2.16 on 2024-11-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_tradinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsegment',
            name='Exchange',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subsegment',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
