# Generated by Django 4.2.16 on 2024-12-03 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_subsegment_exchange_subsegment_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBrokerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_API_SKEY', models.CharField(blank=True, max_length=250, null=True)),
                ('broker_API_UID', models.CharField(blank=True, max_length=50, null=True)),
                ('broker_Demate_User_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('broker_Totp_Authcode', models.CharField(blank=True, max_length=250, null=True)),
                ('broker_pass', models.CharField(blank=True, max_length=50, null=True)),
                ('broker_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.broker')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
