# Generated by Django 4.2.16 on 2024-12-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_clientbrokerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='order_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
