# Generated by Django 4.2.16 on 2024-12-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_tradeorderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='broker',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
