# Generated by Django 4.2.16 on 2024-12-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_tradeorderhistory_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='orderlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderlog',
            name='user',
        ),
    ]
