# Generated by Django 4.2.16 on 2024-12-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_remove_orderlog_failure_reason_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLog',
            new_name='SignalOrderLog',
        ),
    ]
