# Generated by Django 4.2.16 on 2024-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_rename_orderlog_signalorderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='order_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
