# Generated by Django 4.2.16 on 2024-12-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_tradeorderhistory_order_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsegment',
            name='segment',
        ),
    ]
