# Generated by Django 4.2.16 on 2024-12-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_remove_subsegment_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsegment',
            name='segment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_segments', to='main.segment'),
            preserve_default=False,
        ),
    ]
