# Generated by Django 4.2.16 on 2024-12-19 12:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='created_at',
            field=models.DateTimeField(default=main.models.get_ist_time),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='updated_at',
            field=models.DateTimeField(default=main.models.get_ist_time),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=main.models.get_ist_time),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=main.models.get_ist_time),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(default=main.models.get_ist_time),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='trade_date',
            field=models.DateTimeField(default=main.models.get_ist_time),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=main.models.get_ist_time),
        ),
    ]
