# Generated by Django 4.2.16 on 2024-12-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_alter_kyc_created_at_alter_kyc_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_expiry_status',
            field=models.BooleanField(default=False),
        ),
    ]
