# Generated by Django 4.2.16 on 2024-12-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_user_client_expiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Entry_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Entry_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Exit_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Index_Symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Segment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='SignalEntry_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='SignalExit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='startegy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
