# Generated by Django 4.2.16 on 2024-12-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_tradeorderhistory_entry_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeorderhistory',
            old_name='startegy',
            new_name='strategy',
        ),
    ]
