# Generated by Django 4.2.16 on 2024-12-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_rename_startegy_tradeorderhistory_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Entry_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Exit_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='LivePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Lot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='Entry_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='Exit_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
