# Generated by Django 4.2.16 on 2024-12-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_tradeorderhistory_entry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Exit_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
