# Generated by Django 4.2.16 on 2024-12-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_tradeorderhistory_exit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='webhook_signal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
