# Generated by Django 4.2.16 on 2024-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_tradeorderhistory_webhook_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='Index_Symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='broker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='trading_symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
