# Generated by Django 4.2.16 on 2025-01-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_alter_tradeorderhistory_index_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbrokerdetails',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientbrokerdetails',
            name='access_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbrokerdetails',
            name='request_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
