# Generated by Django 4.2.16 on 2025-01-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_clientbrokerdetails_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='order_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
