# Generated by Django 4.2.16 on 2025-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_alter_tradeorderhistory_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='order_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
