# Generated by Django 4.2.16 on 2025-01-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_alter_tradeorderhistory_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='trade_order_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
