# Generated by Django 4.2.16 on 2025-01-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_tradeorderhistory_trade_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Entry_Qty',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='Exit_Qty',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
