# Generated by Django 4.2.16 on 2025-01-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_tradeorderhistory_entry_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeorderhistory',
            name='Entry_Qty',
        ),
        migrations.RemoveField(
            model_name='tradeorderhistory',
            name='Exit_Qty',
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='EntryQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='ExitQty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
