# Generated by Django 4.2.16 on 2025-01-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_remove_tradeorderhistory_entry_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbrokerdetails',
            name='broker_API_KEY',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
