# Generated by Django 4.2.16 on 2025-01-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_clientbrokerdetails_broker_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('company_support_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('company_phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySmtpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.PositiveIntegerField(blank=True, null=True)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
