# Generated by Django 4.2.16 on 2025-01-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_companyprofiledetails_companysmtpdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofiledetails',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
