# Generated by Django 4.2.16 on 2025-01-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_alter_companyprofiledetails_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofiledetails',
            name='company_phone_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
