# Generated by Django 4.2.16 on 2025-01-31 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_alter_companyprofiledetails_company_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofiledetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysmtpdetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_smtp', to=settings.AUTH_USER_MODEL),
        ),
    ]
