# Generated by Django 4.2.16 on 2025-01-31 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_companyprofiledetails_user_companysmtpdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_qty', models.IntegerField(blank=True, null=True)),
                ('license_price', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('sub_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_license', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
