# Generated by Django 4.2.16 on 2025-02-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_adminlicense_created_at_adminlicense_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofiledetails',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofiledetails',
            name='help_center_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofiledetails',
            name='login_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
