# Generated by Django 4.2.16 on 2025-02-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_companyprofiledetails_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofiledetails',
            name='company_sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
