# Generated by Django 4.2.16 on 2025-02-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_companyprofiledetails_company_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbrokerdetails',
            name='request_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
