# Generated by Django 4.2.16 on 2025-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_alter_clientbrokerdetails_request_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbrokerdetails',
            name='request_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
