# Generated by Django 4.2.16 on 2025-02-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_alter_clientbrokerdetails_request_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbrokerdetails',
            name='request_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
