# Generated by Django 4.2.16 on 2025-02-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_alter_clientbrokerdetails_request_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='sl_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeorderhistory',
            name='stop_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
