# Generated by Django 4.2.16 on 2025-02-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_tradeorderhistory_sl_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeorderhistory',
            name='sl_type',
        ),
        migrations.RemoveField(
            model_name='tradeorderhistory',
            name='stop_loss',
        ),
        migrations.AddField(
            model_name='clienttradesetting',
            name='sl_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienttradesetting',
            name='stop_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
