# Generated by Django 4.2.16 on 2025-02-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_remove_tradeorderhistory_sl_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttradesetting',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
