# Generated by Django 4.2.16 on 2025-02-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_clienttradesetting_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorderhistory',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
