# Generated by Django 4.2.16 on 2025-02-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_tradeorderhistory_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='order_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorderhistory',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
