# Generated by Django 4.2.16 on 2025-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_alter_tradeorderhistory_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
