# Generated by Django 4.2.16 on 2025-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_websocketdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websocketdetails',
            name='Auth_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
