# Generated by Django 4.2.16 on 2025-02-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_alter_websocketdetails_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttradesetting',
            name='is_tread_status',
            field=models.BooleanField(default=False),
        ),
    ]
