# Generated by Django 4.2.16 on 2025-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_alter_clienttradesetting_is_tread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbrokerdetails',
            name='isTokenExpired',
            field=models.BooleanField(default=False),
        ),
    ]
