# Generated by Django 4.2.16 on 2025-02-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_clientbrokerdetails_istokenexpired'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbrokerdetails',
            name='tokenCreatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
