# Generated by Django 4.2.16 on 2025-02-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_clientbrokerdetails_tokencreatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbrokerdetails',
            name='isTokenExpired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
