# Generated by Django 4.2.16 on 2025-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_alter_clientbrokerdetails_istokenexpired'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupservice',
            name='Strategy',
            field=models.ManyToManyField(blank=True, related_name='client_Group_service_strategy', to='main.strategies'),
        ),
    ]
