# Generated by Django 4.2.16 on 2025-02-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_tradeorderhistory_groupservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttradesetting',
            name='GroupService',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
