# Generated by Django 4.2.16 on 2025-02-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_clienttradesetting_groupservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttradesetting',
            name='GroupService',
        ),
        migrations.AddField(
            model_name='clienttradesetting',
            name='group_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.groupservice'),
        ),
    ]
