# Generated by Django 4.2.16 on 2025-02-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_remove_clienttradesetting_groupservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttradesetting',
            name='group_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
