# Generated by Django 4.2.16 on 2025-03-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_alter_clienttradesetting_group_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbrokerdetails',
            name='refreshToken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientbrokerdetails',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
