# Generated by Django 4.2.16 on 2025-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_clientbrokerdetails_refreshtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttradesetting',
            name='max_loss_for_day',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
