# Generated by Django 4.2.16 on 2025-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_alter_clienttradesetting_max_loss_for_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttradesetting',
            name='max_loss_for_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clienttradesetting',
            name='trade_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
