# Generated by Django 4.2.16 on 2025-03-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0129_alter_clienttradesetting_max_loss_for_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttradesetting',
            name='trade_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
