# Generated by Django 4.2.16 on 2025-03-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0130_alter_clienttradesetting_trade_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='websocketdetails',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
