# Generated by Django 4.2.16 on 2025-03-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_websocketdetails_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
