# Generated by Django 4.2.16 on 2025-03-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofiledetails',
            name='company_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='company_favicon/'),
        ),
    ]
