from django.conf import settings
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from main.permissions import RolePermissionListView, UpdateRolePermissionsView
from .views import *
from django.conf.urls.static import static

from main import views
urlpatterns = [
    path('signup/', UserRegistrationView.as_view(), name='user-registration'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify-otp/', OTPVerifyView.as_view(), name='otp_verify'),
    path('resend-otp/', ResendOTPView.as_view(), name='resend_otp'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('password-reset-request/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('password-reset-confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('create-roles/', RoleListCreateView.as_view(), name='role-list-create'),
    path('get-role-subadmin/', GetRoleListAPIView.as_view(), name='get-sub-admin-role-list'),
    path('get-roles-list/', GetRoleListAPIView.as_view(), name='role-list'),
    path('delete-roles/<int:id>/', RoleDeleteView.as_view(), name='role-delete'),
    path('roles/<int:pk>/', RoleDetailView.as_view(), name='role-detail'),
    path('user/<int:pk>/', GetUser.as_view(), name='GetUser'),
    path('users/<int:pk>/assign-role/', UserAssignRoleView.as_view(), name='assign-role'),
    path('users-list/', UserManagementView.as_view(), name='user-management'),
    path('create-user/', UserManagementView.as_view(), name='user-management'),
    path('update-user/<int:pk>/', UserManagementView.as_view(), name='user-management'),
    path('delete-user/<int:pk>/', UserManagementView.as_view(), name='user-detail-management'),
    path('user-profile/', UserProfileView.as_view(), name='user-profile'),
    path('kyc/', GetKYCView.as_view(), name='get-kyc'),
    path('get-kyc-by-id/<int:pk>/', GetKYCByIdView.as_view(), name='get-kyc-by-id'),
    path('kyc/update/', CreateOrUpdateKYCView.as_view(), name='create-update-kyc'),
    path('pending-kyc-list/', PendingKYCListView.as_view(), name='kyc-pending-list'),
    path('kyc/verify/<int:kyc_id>/', KYCVerificationView.as_view(), name='kyc-verification'),
    path('update-role-permissions/<int:role_id>/', UpdateRolePermissionsView.as_view(), name='update-role-permissions'),
    path('role-permissions/', RolePermissionListView.as_view(), name='role-permissions-list'),
    path('v1/algo/webhook/', PlaceOrderWebhookView.as_view(), name='webhook'),
    path('get-alice-orders/', GetAliceOrderBook.as_view(), name='get-order-book'),
    path('get-alice-tread-history/', GetAliceTreadBook.as_view(), name='get-tread-book'),
    path('order-logs-list/', OrderLogListView.as_view(), name='order-log-list'),
    path('user-activity-logs/', UserActivityLogListView.as_view(), name='user-activity-logs'),
    path('user-last-login/', LastLoginActivityView.as_view(), name='last-login'),
    path('get-city-data/',Get_city_data.as_view(), name='cites'),
    path('cities/search/', CitySearchView.as_view(), name='city-search'),
    path('get-state-data/',GetStatesView.as_view(), name='cites'),
    path('state/search/', SearchStatesView.as_view(), name='state-search'),
    path('get-segments/', SegmentAPIView.as_view(), name='segment-list-create'),  
    path('create-segments/', SegmentAPIView.as_view(), name='post-segment-detail'), 
    path('update-segments/<int:pk>/', SegmentAPIView.as_view(), name='edit-segment-detail'),  
    path('delete-segments/<int:pk>/', SegmentAPIView.as_view(), name='delete-segment-detail'), 
    path('create-category/', CategoryAPIView.as_view(), name='category-create'), 
    path('get-category/', CategoryAPIView.as_view(), name='category-detail'), 
    path('update-category/<int:pk>/', CategoryAPIView.as_view(), name='update-category-detail'), 
    path('delete-category/<int:pk>/', CategoryAPIView.as_view(), name='delete-category-detail'), 
    path('create-License/', LicenseAPIView.as_view(), name='License-create'), 
    path('get-License/', LicenseAPIView.as_view(), name='License-detail'), 
    path('update-License/<int:pk>/', LicenseAPIView.as_view(), name='update-License-detail'), 
    path('delete-License/<int:pk>/', LicenseAPIView.as_view(), name='delete-License-detail'),
    path('get-services/', ServiceAPIView.as_view(), name='service-list'),
    path('create-services/', ServiceAPIView.as_view(), name='create-service'),
    path('update-services/<int:pk>/', ServiceAPIView.as_view(), name='update-service-detail'),
    path('delete-services/<int:pk>/', ServiceAPIView.as_view(), name='delete-service-detail'),
    path('get-group-service/',GroupServiceView.as_view(),name='group-view'),
    path('create-group-service/',GroupServiceView.as_view(),name='group-create'),
    path('update-group-service/<int:pk>/',GroupServiceView.as_view(),name='update-group-view'),
    path('delete-group-service/<int:pk>/',GroupServiceView.as_view(),name='delete-group-view'),
    path('delete-groupservice-json/<int:pk>/', GroupServiceView.as_view(), name='update-group-json-detail'),
    path('edit-groupservice-json/<int:pk>/', GroupServiceJsonUpdateView.as_view(), name='update-group-service-detail'),
    path('add-strategies/', StrategyAPIView.as_view(), name='add-strategy-list'),
    path('get-strategies/', StrategyAPIView.as_view(), name='get-strategy-list'),
    path('update-strategies/<int:pk>/', StrategyAPIView.as_view(), name='update-strategy-detail'),
    path('delete-strategies/<int:pk>/', StrategyAPIView.as_view(), name='delete-strategy-detail'),
    path('add-broker/', BrokerView.as_view(), name='add-broker-list'),
    path('get-broker/', BrokerView.as_view(), name='get-broker-list'),
    path('update-broker/<int:pk>/', BrokerView.as_view(), name='update-broker-detail'),
    path('delete-broker/<int:pk>/', BrokerView.as_view(), name='delete-broker-detail'),
    path('get-strategies-by-id/<int:pk>/', GetStrategyAPIView.as_view(), name='strategies'),
    path('get-strategies-client/<int:pk>/', GetStrategyAPIView.as_view(), name='get-strategy-client'),
    path('get-Groupservices-by-id/<int:pk>/', GetGroupServiceAPIView.as_view(), name='groupservice'),
    path('get-services-Qty_details/<int:id>/', Group_ServicesQtyAPIView.as_view(), name='Services-Qty'),
    path('create-client/', ClientCreateView.as_view(), name='create-client'),
    path('get-client-list/', ClientCreateView.as_view(), name='get-client'),
    path('get-strategy-clients-list/', ClientCreateView.as_view(), name='get-client'),
    path('update-client/<int:pk>/', ClientCreateView.as_view(), name='update-client'),
    path('delete-client/<int:pk>/', ClientCreateView.as_view(), name='delete-client'),
    path('assign-client-to-strategy/<int:pk>/', AssignClientToStrategyAPIView.as_view(), name='assign-client-to-strategy'),
    path('get-client-by-id/<int:pk>/', GetclientbyidPIView.as_view(), name='subuser-list'),
    path('enable-client/<int:pk>/', ClientCreateView.as_view(), name='update-client'),
    path('get-client-services/<int:pk>/', ClientTreadSettingView.as_view(), name='get-client-services'),
    path('update-client-trading-setting/<int:pk>/', ClientTreadSettingView.as_view(), name='update-client-trading'),
    path('expiry-clients-list/', ClientsDataView.as_view(), name='expiry-clients'),
    path('api/segments/', SubSegmentsView.as_view(), name='sub_segments'),
    path('update-trade-status/', UpdateTradeSettingStatusView.as_view(), name='update_client_setting'),
    path('client-trade-settings/update/', UpdateClientTradeSettingAPIView.as_view(), name='update-trade-setting'),
    path('get-client-trade-setting/', GetTradeSettingAPIView.as_view(), name='get-trade-settings'),
    #  path('update-trade-status/', UpdateTradeStatusView.as_view(), name='update_client_setting'),
 
    path('get-client-segments-list/', UpdateTradeSettingStatusView.as_view(), name='get-trade-settings'),
    # path('get-count-client/',SubAdminAllClientView.as_view(),name='active-inactive-client')
    path('active-inactive-clients/<int:id>/', clientActiveInactiveView.as_view(), name='user-detail'),
    path('clients-by-group-service/<int:group_service_id>/', ClientsByGroupServiceView.as_view(), name='clients-by-group-service'),
    path('active-client-list/', ActiveClientsView.as_view(), name='get-active-client-list'),
    path('inactive-client-list/',InactiveClientsView.as_view(),name='get-inactive-client-list'),
    path('all-subadmins-list/', UserManagementView.as_view(), name='user-management'),
    path("order-webhook/",PlaceOrderWebhookView.as_view(),name='create-order-webhook'),
    path("get-client-trade/",GetclientdataView.as_view(),name='get-client-trade'),
    path('strategies/<int:strategy_id>/clients/', StrategyClientListView.as_view(), name='strategy-client-list'),
    path("get-client-details/",ClientDashboardIView.as_view(),name='get-client-details'),
    path("get-client-Trade-status/",ClientsTradeStatusView.as_view(),name='active-inactive-client'),
    path("update-client-broker/", ClientBrokerDetailsView.as_view(), name='update-client-broker'),
    path("enable-disable-broker/", EnableDisableBrokerView.as_view(), name='update-status-broker'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

