"""
Django settings for algoview project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from decouple import config
import os
from pathlib import Path
import logging
import logging.config
from urllib.parse import urlparse
from django.core.exceptions import ImproperlyConfigured


def _env_bool(value):
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    normalized = str(value).strip().lower()
    if normalized in {"1", "true", "yes", "on", "debug"}:
        return True
    if normalized in {"0", "false", "no", "off", "release", "prod", "production"}:
        return False
    return bool(value)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APP_ENV = config("APP_ENV", default="development").strip().lower()
IS_TEST = APP_ENV == "test" or "PYTEST_CURRENT_TEST" in os.environ
IS_PRODUCTION = APP_ENV in {"production", "prod", "staging"}


def _require(name, value):
    if value in (None, "", []):
        raise ImproperlyConfigured(f"{name} must be configured")
    return value


def _append_unique(items, value):
    if not value or value in items:
        return items
    items.append(value)
    return items


def _csv_config(name, default=""):
    return [
        item.strip()
        for item in config(name, default=default).split(",")
        if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if IS_PRODUCTION:
    SECRET_KEY = _require("DJANGO_SECRET_KEY", config('DJANGO_SECRET_KEY', default=''))
else:
    SECRET_KEY = config('DJANGO_SECRET_KEY', default='dev-only-secret-key-change-before-shared-use')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=_env_bool)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DEBUG must be disabled in production/staging")
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='',
    cast=lambda value: [item.strip() for item in value.split(',') if item.strip()],
)
if IS_PRODUCTION and (not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS):
    raise ImproperlyConfigured("ALLOWED_HOSTS must be explicitly configured in production/staging")
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=_env_bool)
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = CORS_ALLOW_ALL_ORIGINS
if IS_PRODUCTION and CORS_ALLOW_ALL_ORIGINS:
    raise ImproperlyConfigured("CORS_ALLOW_ALL_ORIGINS must be disabled in production/staging")
FILE_UPLOAD_PERMISSIONS = 0o644
X_FRAME_OPTIONS = config("X_FRAME_OPTIONS", default="DENY" if IS_PRODUCTION else "SAMEORIGIN")

CSRF_TRUSTED_ORIGINS = [
    "https://sparksadmin.algoview.in",
    "https://client.algoview.in",
    "https://www.client.algoview.in",
    "https://www.admin.algoview.in",
    "http://www.admin.algoview.in"
]
for origin in _csv_config("CSRF_TRUSTED_ORIGINS"):
    _append_unique(CSRF_TRUSTED_ORIGINS, origin)

CORS_ALLOWED_ORIGINS = [
    "http://103.120.178.54:4000",
    "https://www.admin.algoview.in",
    "https://client.algoview.in",
    "https://sparksadmin.algoview.in"
]
for origin in _csv_config("CORS_ALLOWED_ORIGINS"):
    _append_unique(CORS_ALLOWED_ORIGINS, origin)

FRONTEND_APP_URL = config("FRONTEND_APP_URL", default="").rstrip("/")
UPSTOX_REDIRECT_URL = config("UPSTOX_REDIRECT_URL", default="").strip()

if UPSTOX_REDIRECT_URL:
    parsed_upstox_redirect = urlparse(UPSTOX_REDIRECT_URL)
    upstox_origin = f"{parsed_upstox_redirect.scheme}://{parsed_upstox_redirect.netloc}" if parsed_upstox_redirect.scheme and parsed_upstox_redirect.netloc else ""
    upstox_host = parsed_upstox_redirect.hostname or ""
    _append_unique(CSRF_TRUSTED_ORIGINS, upstox_origin)
    _append_unique(CORS_ALLOWED_ORIGINS, upstox_origin)
    _append_unique(ALLOWED_HOSTS, upstox_host)

WEBHOOK_SECRET = config("WEBHOOK_SECRET", default="")
if IS_PRODUCTION:
    _require("WEBHOOK_SECRET", WEBHOOK_SECRET)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'rest_framework_simplejwt',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'main',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
     'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Add this line
    'corsheaders.middleware.CorsMiddleware',
]



ROOT_URLCONF = 'algoview.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'main/templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'algoview.wsgi.application'

ASGI_APPLICATION = 'algoview.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# Database settings
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3' if not IS_PRODUCTION else '')
DB_NAME = config('DB_NAME', default=str(BASE_DIR / 'db.sqlite3') if not IS_PRODUCTION else '')
DB_USER = config('DB_USER', default='')
DB_PASSWORD = config('DB_PASSWORD', default='')
DB_HOST = config('DB_HOST', default='')
DB_PORT = config('DB_PORT', default='')

if IS_PRODUCTION:
    _require("DB_ENGINE", DB_ENGINE)
    _require("DB_NAME", DB_NAME)
    if DB_ENGINE == 'django.db.backends.sqlite3':
        raise ImproperlyConfigured("SQLite is not allowed in production/staging")

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}

AUTH_USER_MODEL = 'main.User'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'
# USE_TZ = True

USE_I18N = True

USE_TZ = True

SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=_env_bool)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=_env_bool)
CSRF_COOKIE_HTTPONLY = False
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=IS_PRODUCTION, cast=_env_bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000 if IS_PRODUCTION else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=IS_PRODUCTION, cast=_env_bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=IS_PRODUCTION, cast=_env_bool)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# Add this line
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Number of items per page
}


# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default backend
)

REDIS_URL = config('REDIS_URL', default='').strip()
if IS_PRODUCTION:
    _require("REDIS_URL", REDIS_URL)

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=REDIS_URL or 'memory://')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=REDIS_URL or 'cache+memory://')

BROKER_ENCRYPTION_KEYS = config(
    'BROKER_ENCRYPTION_KEYS',
    default='' if IS_PRODUCTION else 'MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=',
)
if IS_PRODUCTION:
    _require("BROKER_ENCRYPTION_KEYS", BROKER_ENCRYPTION_KEYS)
ANGELONE_CALLBACK_STATE_TTL_SECONDS = config('ANGELONE_CALLBACK_STATE_TTL_SECONDS', default=600, cast=int)
ANGELONE_SESSION_TTL_SECONDS = config('ANGELONE_SESSION_TTL_SECONDS', default=43200, cast=int)
ANGELONE_REMOTE_VALIDATION_TTL_SECONDS = config('ANGELONE_REMOTE_VALIDATION_TTL_SECONDS', default=300, cast=int)
ANGELONE_LOGIN_LOCK_SECONDS = config('ANGELONE_LOGIN_LOCK_SECONDS', default=30, cast=int)
ANGELONE_LOGIN_LOCK_WAIT_SECONDS = config('ANGELONE_LOGIN_LOCK_WAIT_SECONDS', default=10, cast=int)
ANGELONE_CIRCUIT_BREAKER_FAILURE_THRESHOLD = config('ANGELONE_CIRCUIT_BREAKER_FAILURE_THRESHOLD', default=5, cast=int)
ANGELONE_CIRCUIT_BREAKER_RECOVERY_SECONDS = config('ANGELONE_CIRCUIT_BREAKER_RECOVERY_SECONDS', default=60, cast=int)
ANGELONE_SESSION_CACHE_PREFIX = config('ANGELONE_SESSION_CACHE_PREFIX', default='angelone:session')
ANGELONE_STATE_CACHE_PREFIX = config('ANGELONE_STATE_CACHE_PREFIX', default='angelone:state')
ANGELONE_LOCK_CACHE_PREFIX = config('ANGELONE_LOCK_CACHE_PREFIX', default='angelone:lock')
ANGELONE_CIRCUIT_CACHE_PREFIX = config('ANGELONE_CIRCUIT_CACHE_PREFIX', default='angelone:circuit')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
        },
        'circuit_breaker': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'algoview-default-cache',
            'TIMEOUT': 300,
        },
        'circuit_breaker': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'algoview-circuit-cache',
            'TIMEOUT': 300,
        },
    }

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC' 

CONTACT_NUM="+919988746583"
REDIRECT_URL=config('BROKER_REDIRECT_URL', default="https://3-109-40-137.sslip.io/api/broker/callback/")
LOGIN_LINK="https://www.admin.algoview.in/login"
HELP_CENTER_LINK="https://www.admin.algoview.in/"
COMPANY_WEBSITE="https://www.admin.algoview.in/" 
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'sanitize_secrets': {
            '()': 'main.logging_filters.SecretRedactionFilter',
        },
    },
    'formatters': {
        'verbose': {  # Formatter to include date and time
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {  # Logs to console (stdout, stderr)
            'level': 'DEBUG',  # Minimum level to log
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',  # Apply the formatter here
            'filters': ['sanitize_secrets'],
        },
        'file': {  # Logs to a file
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/webhooks.log'),  # Ensure this file exists and the directory is writable
            'formatter': 'verbose',  # Apply the formatter here
            'filters': ['sanitize_secrets'],
        },
    },
    'loggers': {
        'django': {  # Logger for general Django logs
            'handlers': ['console', 'file'],
            'level': 'INFO',  # Change to 'DEBUG' if you want more verbose logs
            'propagate': True,
        },
        'main': {  # Logger for your specific app
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # Set this level for your app logs
            'propagate': False,
        },
    },
}

RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default="")
RAZORPAY_SECRET = config('RAZORPAY_SECRET', default="")
